name: Run Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: |
        xcodebuild clean test -project HappyChuseok/HappyChuseok.xcodeproj -scheme HappyChuseok -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
