name: Run Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: HappyChuseok.xcodeproj
        scheme: HappyChuseok
        destination: platform=iOS Simulator
        action: test
